services:
  db:
    image: postgres:17
    restart: unless-stopped
    container_name: postgres_db_2
    env_file:
      - ./.env
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_migrate_2
    command: python manage.py migrate
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: note
    env_file:
      - ./.env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      migrate:
        condition: service_completed_successfully


volumes:
  postgres_data:
  static_volume: