# Generated by Django 6.1.1 on 2026-09-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="название заметки")),
                ("date", models.DateField(auto_now_add=True, verbose_name="дата создания записи")),
                ("text", models.TextField(verbose_name="текст заметки")),
                ("mood", models.CharField(max_length=20, verbose_name="настроение")),
                ("energy", models.PositiveSmallIntegerField(verbose_name="энергия")),
                ("image", models.ImageField(blank=True, null=True, upload_to="note/image/", verbose_name="картинка")),
            ],
            options={
                "verbose_name": "заметка",
                "verbose_name_plural": "заметки",
                "db_table": "note",
                "ordering": ["id"],
                "permissions": [("can_unpublish_note", "Can unpublish note")],
            },
        ),
    ]
